require('dotenv').config();
const Anthropic = require('@anthropic-ai/sdk');
const readline = require('readline');
const { TOOL_DEFINITIONS, executeTool } = require('./tools');

// ─── CONFIGURATION ────────────────────────────────────────────────────────────

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

const SYSTEM_PROMPT = `Tu es un agent autonome IA puissant. Tu as accès à des outils pour:
- Rechercher sur le web (web_search)
- Lire des pages web (read_url)
- Lire et écrire des fichiers locaux (read_file, write_file, list_files)
- Exécuter des commandes shell (run_command)

Comportement:
- Tu travailles de façon AUTONOME: tu enchaînes les outils sans attendre confirmation
- Tu réfléchis étape par étape avant d'agir
- Tu sauvegardes les résultats importants dans des fichiers
- Tu rapportes clairement ce que tu as accompli
- Si une tâche est complexe, tu la décomposes en sous-tâches`;

// ─── BOUCLE AGENTIQUE ─────────────────────────────────────────────────────────

async function runAgent(userTask) {
  console.log('\n' + '='.repeat(60));
    console.log('TACHE:', userTask);
      console.log('='.repeat(60));

        const messages = [{ role: 'user', content: userTask }];
          let iteration = 0;
            const MAX_ITERATIONS = 20;

              while (iteration < MAX_ITERATIONS) {
                  iteration++;
                      console.log(`\n[ITERATION ${iteration}]`);

                          // Appel API Claude
                              const response = await client.messages.create({
                                    model: 'claude-opus-4-5',
                                          max_tokens: 4096,
                                                system: SYSTEM_PROMPT,
                                                      tools: TOOL_DEFINITIONS,
                                                            messages: messages
                                                                });

                                                                    console.log(`[STOP: ${response.stop_reason}]`);

                                                                        // Ajouter la réponse de l'assistant
                                                                            messages.push({ role: 'assistant', content: response.content });

                                                                                // Si l'agent a terminé
                                                                                    if (response.stop_reason === 'end_turn') {
                                                                                          const finalText = response.content
                                                                                                  .filter(b => b.type === 'text')
                                                                                                          .map(b => b.text)
                                                                                                                  .join('\n');
                                                                                                                        console.log('\n' + '─'.repeat(60));
                                                                                                                              console.log('REPONSE FINALE:');
                                                                                                                                    console.log('─'.repeat(60));
                                                                                                                                          console.log(finalText);
                                                                                                                                                return finalText;
                                                                                                                                                    }
                                                                                                                                                    
                                                                                                                                                        // Si l'agent utilise des outils
                                                                                                                                                            if (response.stop_reason === 'tool_use') {
                                                                                                                                                                  const toolUseBlocks = response.content.filter(b => b.type === 'tool_use');
                                                                                                                                                                        const toolResults = [];
                                                                                                                                                                        
                                                                                                                                                                              for (const toolUse of toolUseBlocks) {
                                                                                                                                                                                      console.log(`\n[OUTIL] ${toolUse.name}`);
                                                                                                                                                                                              console.log('[INPUT]', JSON.stringify(toolUse.input, null, 2));
                                                                                                                                                                                              
                                                                                                                                                                                                      const result = await executeTool(toolUse.name, toolUse.input, (msg) => {
                                                                                                                                                                                                                console.log(msg);
                                                                                                                                                                                                                        });
                                                                                                                                                                                                                        
                                                                                                                                                                                                                                console.log('[RESULTAT]', JSON.stringify(result, null, 2).slice(0, 500));
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                        toolResults.push({
                                                                                                                                                                                                                                                  type: 'tool_result',
                                                                                                                                                                                                                                                            tool_use_id: toolUse.id,
                                                                                                                                                                                                                                                                      content: JSON.stringify(result)
                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                          // Retourner les résultats à Claude
                                                                                                                                                                                                                                                                                                messages.push({ role: 'user', content: toolResults });
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                        console.log('[ATTENTION] Nombre maximum d\'itérations atteint');
                                                                                                                                                                                                                                                                                                          return 'Tâche interrompue (max itérations)';
                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                          // ─── INTERFACE INTERACTIVE ────────────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                          async function main() {
                                                                                                                                                                                                                                                                                                            if (!process.env.ANTHROPIC_API_KEY) {
                                                                                                                                                                                                                                                                                                                console.error('ERREUR: ANTHROPIC_API_KEY manquante dans .env');
                                                                                                                                                                                                                                                                                                                    console.error('Créez un fichier .env avec: ANTHROPIC_API_KEY=votre_cle_ici');
                                                                                                                                                                                                                                                                                                                        process.exit(1);
                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                            // Mode ligne de commande: node index.js "votre tâche"
                                                                                                                                                                                                                                                                                                                              if (process.argv[2]) {
                                                                                                                                                                                                                                                                                                                                  const task = process.argv.slice(2).join(' ');
                                                                                                                                                                                                                                                                                                                                      await runAgent(task);
                                                                                                                                                                                                                                                                                                                                          return;
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                              // Mode interactif
                                                                                                                                                                                                                                                                                                                                                const rl = readline.createInterface({
                                                                                                                                                                                                                                                                                                                                                    input: process.stdin,
                                                                                                                                                                                                                                                                                                                                                        output: process.stdout
                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                            console.log('\n╔════════════════════════════════════════╗');
                                                                                                                                                                                                                                                                                                                                                              console.log('║     AGENT AUTONOME IA - Claude          ║');
                                                                                                                                                                                                                                                                                                                                                                console.log('║  Tapez votre tâche et appuyez Entrée   ║');
                                                                                                                                                                                                                                                                                                                                                                  console.log('║  Tapez "exit" pour quitter             ║');
                                                                                                                                                                                                                                                                                                                                                                    console.log('╚════════════════════════════════════════╝\n');
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                      const askQuestion = () => {
                                                                                                                                                                                                                                                                                                                                                                          rl.question('> Tâche: ', async (input) => {
                                                                                                                                                                                                                                                                                                                                                                                const task = input.trim();
                                                                                                                                                                                                                                                                                                                                                                                      if (!task || task.toLowerCase() === 'exit') {
                                                                                                                                                                                                                                                                                                                                                                                              console.log('Au revoir!');
                                                                                                                                                                                                                                                                                                                                                                                                      rl.close();
                                                                                                                                                                                                                                                                                                                                                                                                              return;
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                                                                                  await runAgent(task);
                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('ERREUR:', err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                            askQuestion();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    askQuestion();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    main().catch(console.error);
